### ISSUE TITLE
Extraneous code being displayed on home page

### ISSUE THREAD

**Issue by willingc** [lektor/lektor-website#113]
<img width="929" alt="screen shot 2016-07-22 at 1 28 27 pm" src="https://cloud.githubusercontent.com/assets/2680980/17070371/5a2de3a6-5010-11e6-9d18-0559989523a1.png">

**Comment by nixjdm** [comment]
I have not seen this since I've been around, and this is pretty old. If anything like it pops up again we can make a new issue. When this was posted, I can only speculate that it was a failed webpack build, or bad scss, and was fixed (thanks to your post, perhaps.) I'm sorry no one responded to you, but it does look fixed. Thanks
