### ISSUE TITLE
Json-ld schemas 

### ISSUE THREAD

**Issue by vladp** [lektor/lektor-website#289]
Hello
thank you for making the project available.

Is it possible to enable Json-LD schemas for blog posts
(I searched the docs but could not find info)

**Comment by runfalk** [comment]
Yes it's possible, but there is no built-in solution that you can use. Since the Lektor data model is flexible I don't think it's something we can provide out of the box, or even as a plugin.

You can however edit your template for a blogpost to look something like this (I assume you use the Lektor quickstart).

First you have to wrap the contents of your base `layout.html`'s `<head>`:

```html
<head>
{% block head %}
<title>Everything that used to be in head should be within the block tages</title>
{% end block %}
</head>
```

Then your `blog.html` should have this in it:

```html
{% block head %}
{{ super() }}
<script type="application/ld+json">
{{ {
   "your": "json",
   "ld": ["goes", "here"],
}|json }}
</script>
{% end block %}
```

Maybe we should improve the documentation to include how to do this?

**Comment by vladp** [comment]
ok, thank you. I will try this.
