### ISSUE TITLE
Download button should reference stable release

### ISSUE THREAD

**Issue by dairiki** [lektor/lektor-website#360]
I just noticed that the *Download* button on the front page of the website currently links to a pre-release (3.4.0b4).  It should probably link to the latest stable release (currently 3.3.7).

![image](https://user-images.githubusercontent.com/495018/208253726-6dcb0943-f9af-45a9-8d37-afa43c62750b.png)

----
If we want to continue to use GitHub's [Releases API](https://docs.github.com/en/rest/releases/releases) to access the latest version, we should ignore those releases which have the `prerelease` flag set.

```console
$ curl -s https://api.github.com/repos/lektor/lektor/releases | jq 'first(.[] | select(.prerelease | not)).tag_name'
"v3.3.7"
```

As a perhaps better alternative (since it doesn't rely on one of us — currently manually — creating a GitHub release), the latest stable version appears to be easily accessible via PyPI's [JSON API](https://warehouse.pypa.io/api-reference/json.html).

```console
$ curl -s https://pypi.org/pypi/lektor/json | jq '.info.version'
"3.3.7"
```

**Comment by dairiki** [comment]
Maybe we should call out both the latest stable release and the latest prerelease (if the prerelease is more recent than the stable release)?

**Comment by dairiki** [comment]
Another possibility: Since we now rebuild the site daily we could make the version in the Download button static (determined a site-build-time rather than via Javascript).  There are advantages to each way.  Something to think about...

**Comment by yagebu** [comment]
I think fetching from PyPI is best, since that is the "real" available version. I don't really think pointing out pre-releases is necessary directly on the front page, users can go to PyPI or Github for that information (and users who wouldn't know to look there should probably not install pre-releases...)

I've changed the frontend code to fetch the release info from PyPI: #361 (still dynamically via Javascript)
